enableGlobalCache: true
nmMode: hardlinks-global

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.13.0.cjs

packageExtensions:
  "@carbon/react@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-is:
        optional: true
      sass:
        optional: true

  "@carbon/charts-react@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true

  "@openmrs/esm-patient-common-lib@*":
    peerDependenciesMeta:
      "@openmrs/esm-framework":
        optional: true
      single-spa:
        optional: true

  "@openmrs/esm-framework@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-is:
        optional: true
      react-i18next:
        optional: true
      i18next:
        optional: true
      single-spa:
        optional: true
      swr:
        optional: true
      rxjs:
        optional: true

  "@rspack/cli@*":
    peerDependenciesMeta:
      "@rspack/core":
        optional: true

  "css-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true

  "swc-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true

  "react-i18next@*":
    peerDependenciesMeta:
      i18next:
        optional: true
      typescript:
        optional: true

  "@sihsalus/sihsalus-esm@*":
    peerDependenciesMeta:
      webpack:
        optional: true

  "@openmrs/esm-styleguide@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-is:
        optional: true
      dayjs:
        optional: true
      i18next:
        optional: true
      react-i18next:
        optional: true
      single-spa:
        optional: true
      "@swc/core":
        optional: true
      webpack:
        optional: true

  "i18next@*":
    peerDependenciesMeta:
      typescript:
        optional: true


  "@sihsalus/esm-rbac@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-is:
        optional: true
      i18next:
        optional: true
      react-i18next:
        optional: true
      single-spa:
        optional: true
      swr:
        optional: true
      rxjs:
        optional: true
      webpack:
        optional: true

  "ts-node@*":
    peerDependenciesMeta:
      "@types/node":
        optional: true

  "@swc-node/loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true

  "file-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true

  "swr@*":
    peerDependenciesMeta:
      react:
        optional: true

  "@vitest/ui@*":
    peerDependenciesMeta:
      vitest:
        optional: true

logFilters:
  - code: YN0002
    level: discard
